language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rake db:test:prepare --trace
- bundle exec rspec
deploy:
  provider: heroku
  api_key: 44887bea2881cacd3e7aa9c9a1e39222
  app:
  run: rails db:migrate
