language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rake db:test:prepare --trace
- bundle exec rspec
deploy:
  provider: heroku
  api_key: movie_api
  app:
  run: rails db:migrate
