
default: &default
adapter: postgresql
encoding: unicode
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
<% if ENV['DB_HOST'].present? %>
host: <%= ENV.fetch('DB_HOST') %>
username: <%= ENV.fetch('DB_USERNAME') %>
password: <%= ENV.fetch('DB_PASSWORD') %>
port: <%= ENV.fetch('DB_PORT') %>
<% end %>

development:
  <<: *default
  database: viewing_party_development

production:
  <<: *default
  database: viewing_party_production
  username: viewing_party
  password: <%= ENV['VIEWING_PARTY_DATABASE_PASSWORD'] %>
