default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] { 5 } %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>
  port: <%= ENV['DB_PORT'] || '5432' %>
development:
  <<: *default
  database: viewing_party_development
test:
  <<: *default
  database: viewing_party_test
production:
  <<: *default
  database: viewing_party_production
  username: viewing_party
  password: <%= ENV['VIEWING_PARTY_DATABASE_PASSWORD'] %>
